version: "3.7"
services:
  backend:
    build:
      context: backend
      args:
        - NODE_ENV=development
    command: npm run start
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    ports:
      - 80:80
      - 3000:3000
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    volumes:
      - ./backend:/code
      - /code/node_modules
    networks:
      - public
      - private
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_USER=ce
      - MYSQL_USER_PASSWORD=ce

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend

networks:
  public:
  private:

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
